version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.2
    - 12.6.3
    - 12.7.0
    - 12.7.1
    - 12.7.2
    - 12.7.3
    - 12.8.0
    - 12.8.1
    - 12.8.3
    - 13.0.0
    - 13.0.1
    - 13.0.10
    - 13.0.13
    - 13.0.16
    - 13.0.2
    - 13.0.6
    - 13.0.7
    - 13.1.1
    - 13.1.2
    - 13.1.3
    - 13.1.5
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
    - 5.11.9
  - dependency-name: "@types/bootstrap"
    versions:
    - 5.0.11
    - 5.0.12
    - 5.0.5
    - 5.0.7
    - 5.0.8
    - 5.0.9
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: zope-interface
    versions:
    - 5.3.0
  - dependency-name: pillow
    versions:
    - 8.1.1
    - 8.1.2
  - dependency-name: autobahn
    versions:
    - 21.1.1
    - 21.2.1
    - 21.2.2
  - dependency-name: cryptography
    versions:
    - 3.4.1
    - 3.4.3
  - dependency-name: django
    versions:
    - 3.1.6
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: node
    versions:
    - 15.10.0.pre.buster.pre.slim
    - 15.11.0.pre.buster.pre.slim
    - 15.12.0.pre.buster.pre.slim
    - 15.13.0.pre.buster.pre.slim
    - 15.14.0.pre.buster.pre.slim
    - 15.7.0.pre.buster.pre.slim
    - 15.8.0.pre.buster.pre.slim
    - 15.9.0.pre.buster.pre.slim
  - dependency-name: python
    versions:
    - 3.9.2.pre.slim.pre.buster
    - 3.9.3.pre.slim.pre.buster
