language: python
os: linux
dist: focal

cache:
  - pip
  - npm

jobs:
  include:
    - stage: Test Python
      language: python
      python:
        - "3.8"
      install: pip install -r requirements.txt
      script: pytest 
    - stage: Test Node.js
      language: node_js
      node_js:
        - "14"
      install: npm i
      script: npm test
    - stage: Production
      python: "3.8"
      node_js: "14"
      install:
        - pip install -r requirements.txt
        - npm i
      script:
        - npm run build
        - python manage.py collectstatic --no-input
