language: python
os: linux
dist: focal

cache:
  - pip
  - npm

jobs:
  include:
    - stage: Test Python
      language: python
      python:
        - "3.8"
      install:
        - pip install -r requirements.txt
        - pip install pytest pytest-django coverage
      script: 
        - coverage run --source=. manage.py test
        - coverage report -m 
      
    - stage: Test Node.js
      language: node_js
      node_js:
        - "14"
      install: npm i
      script: npm test
